### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by MengNianxiaoyao** [MengNianxiaoyao/friends#12]
```yaml
- blog: 呆鱼
  name: 呆鱼
  url: https://daiyu.fun/
  avatar: https://daiyu.fun/img/avatar.png
  desc: 命运之所以称为命运，正是因为它无可改变。
  color: '#455cef'
```
