### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by MengNianxiaoyao** [MengNianxiaoyao/friends#13]
```yaml
- blog: Fomalhaut🥝🥝
  name: Fomalhaut
  url: https://www.fomal.cc/
  avatar: https://www.fomal.cc/assets/head.jpg
  desc: Future is now 🍭🍭🍭
  color: '#0078e7'
```
