### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by MengNianxiaoyao** [MengNianxiaoyao/friends#15]
### 检查清单

- [x] 合法的、非营利性、无商业广告、无木马植入。
- [x] 有实质性原创内容的 HTTPS 站点，发布过至少 5 篇原创文章，内容题材不限。
- [x] 最好有独立域名。
- [x] 博客正常运行，非刚搭建好。

### 友链信息

```yaml
- blog: 安知鱼
  name: 安知鱼
  url: https://blog.anheyu.cd/
  avatar: https://img01.anheyu.com/useruploads/90/2023/04/23/6444e85234e51.jpg
  desc: 生活明朗，万物可爱
  color: '#455cef'
```

### 友链地址

https://blog.anheyu.cd/
