### ISSUE TITLE
[友链] 测试

### ISSUE THREAD

**Issue by MengNianxiaoyao** [MengNianxiaoyao/friends#25]
### 检查清单

- [x] 合法的、非营利性、无商业广告、无木马植入。
- [x] 有实质性原创内容的 HTTPS 站点，发布过至少 5 篇原创文章，内容题材不限。
- [x] 博客正常运行，非刚搭建好。
- [x] 最好有独立域名。

### 友链信息

```yaml
- blog: 呆鱼
  name: 呆鱼
  url: https://daiyu.cc/
  avatar: https://daiyu.fun/img/avatar.png
  desc: 命运之所以称为命运，正是因为它无可改变。
  color: '#455cef'
```

### 友链地址

https://daiyu.cc/
